name: Cypress Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest # Choosing OS
        strategy:
            matrix:
                node-version: [14.17.0]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: Install dependencies # install npm packages
              run: npm ci 
            - name: run tests
              run: npx cypress run --browser chrome
            - uses: actions/upload-artifact@v2
              if: always()
              with:
                name: videos
                path: cypress/videos/
                retention-days: 30
            - uses: actions/upload-artifact@v2
              if: always()
              with:
                name: screenshots
                path: cypress/screenshots/
                retention-days: 30

